version: '3.8'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    entrypoint:
      - /app/jobbuzz-api
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8090:8080

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
