version: '3.1'

services:

  db:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: jobbuzz
      MYSQL_USER: jobbuzz
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8090:8080

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

