// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type NewJob struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
